language: java
jdk:
  - openjdk8

branches:
  only:
    - master

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/entrysystem/.m2/repository'
    - '$HOME/entrysystem/.gradle'

script: "cd entrysystem && ./gradlew clean build"

# CI 실행 완료시 메일, Slack으로 알람
notifications:
  email:
    recipients:
      - nooheat1228@gmail.com
  slack: entrydsm:zOnjAdsIqLI4Ob9rpiwiAZzw
    
